name: Luacheck
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Luacheck linter
      - uses: nebularg/actions-luacheck@v1
        with:
          files: ./lina_witches_of_the_moon.p8
          args: -qo 011
